[package]
name = "skel"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.71"
clap = { version = "4.2.7", features = ["derive"] }
dialoguer = "0.10.4"
dirs = "5.0.1"
skim = "0.10.4"
tempdir = "0.3.7"
walkdir = "2.3.3"
